# remote_theme: jekyll/minima
# OR remove the line entirely
title: A Cubed GIMP Docs
description: GIMP 3 Python and PDB class references by A³BS
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty
